openapi: 3.0.0
info:
  title: CBRE API
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /users:
    $ref: "./paths/users.yaml"
components:
  schemas:
    $ref: "./components/schemas.yaml"
  responses:
    $ref: "./components/responses.yaml"
