openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Hello メッセージ取得
      responses:
        '200':
          description: 正常レスポンス
          content:
            application/json:
              example:
                message: "Hello, world!"
